/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Graph_H
#define Graph_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "testv2_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GraphIf {
 public:
  virtual ~GraphIf() {}
  virtual int32_t createSpace(const std::string& req) = 0;
};

class GraphIfFactory {
 public:
  typedef GraphIf Handler;

  virtual ~GraphIfFactory() {}

  virtual GraphIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GraphIf* /* handler */) = 0;
  };

class GraphIfSingletonFactory : virtual public GraphIfFactory {
 public:
  GraphIfSingletonFactory(const ::std::shared_ptr<GraphIf>& iface) : iface_(iface) {}
  virtual ~GraphIfSingletonFactory() {}

  virtual GraphIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(GraphIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<GraphIf> iface_;
};

class GraphNull : virtual public GraphIf {
 public:
  virtual ~GraphNull() {}
  int32_t createSpace(const std::string& /* req */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Graph_createSpace_args__isset {
  _Graph_createSpace_args__isset() : req(false) {}
  bool req :1;
} _Graph_createSpace_args__isset;

class Graph_createSpace_args {
 public:

  Graph_createSpace_args(const Graph_createSpace_args&);
  Graph_createSpace_args& operator=(const Graph_createSpace_args&);
  Graph_createSpace_args() noexcept
                         : req() {
  }

  virtual ~Graph_createSpace_args() noexcept;
  std::string req;

  _Graph_createSpace_args__isset __isset;

  void __set_req(const std::string& val);

  bool operator == (const Graph_createSpace_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const Graph_createSpace_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Graph_createSpace_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Graph_createSpace_pargs {
 public:


  virtual ~Graph_createSpace_pargs() noexcept;
  const std::string* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Graph_createSpace_result__isset {
  _Graph_createSpace_result__isset() : success(false) {}
  bool success :1;
} _Graph_createSpace_result__isset;

class Graph_createSpace_result {
 public:

  Graph_createSpace_result(const Graph_createSpace_result&) noexcept;
  Graph_createSpace_result& operator=(const Graph_createSpace_result&) noexcept;
  Graph_createSpace_result() noexcept
                           : success(0) {
  }

  virtual ~Graph_createSpace_result() noexcept;
  int32_t success;

  _Graph_createSpace_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Graph_createSpace_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Graph_createSpace_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Graph_createSpace_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Graph_createSpace_presult__isset {
  _Graph_createSpace_presult__isset() : success(false) {}
  bool success :1;
} _Graph_createSpace_presult__isset;

class Graph_createSpace_presult {
 public:


  virtual ~Graph_createSpace_presult() noexcept;
  int32_t* success;

  _Graph_createSpace_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GraphClient : virtual public GraphIf {
 public:
  GraphClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GraphClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t createSpace(const std::string& req) override;
  void send_createSpace(const std::string& req);
  int32_t recv_createSpace();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GraphProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<GraphIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (GraphProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_createSpace(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GraphProcessor(::std::shared_ptr<GraphIf> iface) :
    iface_(iface) {
    processMap_["createSpace"] = &GraphProcessor::process_createSpace;
  }

  virtual ~GraphProcessor() {}
};

class GraphProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GraphProcessorFactory(const ::std::shared_ptr< GraphIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< GraphIfFactory > handlerFactory_;
};

class GraphMultiface : virtual public GraphIf {
 public:
  GraphMultiface(std::vector<std::shared_ptr<GraphIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GraphMultiface() {}
 protected:
  std::vector<std::shared_ptr<GraphIf> > ifaces_;
  GraphMultiface() {}
  void add(::std::shared_ptr<GraphIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t createSpace(const std::string& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->createSpace(req);
    }
    return ifaces_[i]->createSpace(req);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GraphConcurrentClient : virtual public GraphIf {
 public:
  GraphConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  GraphConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t createSpace(const std::string& req) override;
  int32_t send_createSpace(const std::string& req);
  int32_t recv_createSpace(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
